export interface IProject {
    name: string,
    date: string,
    subtitle: string,
    text: string,
    color: string,
    logo: string,
    desc: string,
    tags: string[],
    repoUrl: string,
    liveUrl: string,
    xdUrl: string,
    unityUrl: string,
    screenshot1: string,
    screenshot2: string,
    screenshot3: string,
    expandedDescription: string,
    importance: number,
    technologies: string[]
}
